name: CI Docker Build & Push

on:
  push:
    branches:
      - lab-trivy

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ci-html-demo
      IMAGE_TAG: latest
      DOCKER_REGISTRY: lindsey27

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build de l’image Docker
        run: |
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

      - name: Test de l’image Docker
        run: |
          docker image ls $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Push des l’image Docker
        run: |
    

          docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Scan Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1
          vuln-type: os,library
          ignore-unfixed: true